-- CRIANDO O SCHEMA E USANDO-O
DROP SCHEMA EST_CASOIII;
CREATE SCHEMA EST_CASOIII;
USE EST_CASOIII;

#criando as tabelas sem chave estrangeira
CREATE TABLE IF NOT EXISTS CLIENTES(
    CLI_ID INT PRIMARY KEY,
    CLI_CNPJ VARCHAR(14) NOT NULL,
    CLI_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    CLI_RAMO_ATIVIDADE TEXT NOT NULL,
    CLI_DATA_CAD DATE NOT NULL
);

-- ALTER TABLE para CLIENTES
ALTER TABLE CLIENTES ADD COLUMN CLI_EMAIL VARCHAR(50);
ALTER TABLE CLIENTES CHANGE COLUMN CLI_EMAIL CLI_EMAIL_NOVO VARCHAR(50);
ALTER TABLE CLIENTES MODIFY COLUMN CLI_EMAIL_NOVO VARCHAR(100);
ALTER TABLE CLIENTES DROP COLUMN CLI_EMAIL_NOVO;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    FORN_CNPJ VARCHAR(14) PRIMARY KEY,
    FORN_RAZAO_SOCIAL VARCHAR(100) NOT NULL
);

-- ALTER TABLE para FORNECEDORES
ALTER TABLE FORNECEDORES ADD COLUMN FORN_EMAIL VARCHAR(50);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORN_EMAIL FORN_EMAIL_NOVO VARCHAR(50);
ALTER TABLE FORNECEDORES MODIFY COLUMN FORN_EMAIL_NOVO VARCHAR(100);
ALTER TABLE FORNECEDORES DROP COLUMN FORN_EMAIL_NOVO;

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTES(
    TC_ID INT PRIMARY KEY,
    TC_NOME VARCHAR(50) NOT NULL
);

-- ALTER TABLE para TIPO_COMPONENTES
ALTER TABLE TIPO_COMPONENTES ADD COLUMN TC_DESCRICAO TEXT;
ALTER TABLE TIPO_COMPONENTES CHANGE COLUMN TC_DESCRICAO TC_DESCRICAO_NOVA TEXT;
ALTER TABLE TIPO_COMPONENTES MODIFY COLUMN TC_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE TIPO_COMPONENTES DROP COLUMN TC_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS COMPONENTES(
    COMP_ID INT PRIMARY KEY,
    COMP_TIPO VARCHAR(50) NOT NULL,
    COMP_NOME VARCHAR(50) NOT NULL,
    COMP_QTD_ESTOQUE INT NOT NULL,
    COMP_PRECO_UN DECIMAL(10,3) NOT NULL,
    COMP_UN INT NOT NULL
);

-- ALTER TABLE para COMPONENTES
ALTER TABLE COMPONENTES ADD COLUMN COMP_DESCRICAO TEXT;
ALTER TABLE COMPONENTES CHANGE COLUMN COMP_DESCRICAO COMP_DESCRICAO_NOVA TEXT;
ALTER TABLE COMPONENTES MODIFY COLUMN COMP_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE COMPONENTES DROP COLUMN COMP_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS MAQUINAS(
    MAQ_ID INT PRIMARY KEY,
    MAQ_TEMPO_VIDA VARCHAR(50) NOT NULL,
    MAQ_DATA_COMPRA DATE NOT NULL,
    MAQ_DATA_FIM_GAR DATE NOT NULL
);

-- ALTER TABLE para MAQUINAS
ALTER TABLE MAQUINAS ADD COLUMN MAQ_DESCRICAO TEXT;
ALTER TABLE MAQUINAS CHANGE COLUMN MAQ_DESCRICAO MAQ_DESCRICAO_NOVA TEXT;
ALTER TABLE MAQUINAS MODIFY COLUMN MAQ_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE MAQUINAS DROP COLUMN MAQ_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS(
    RE_ID INT PRIMARY KEY,
    RE_QTD_NEC INT NOT NULL,
    RE_UN INT NOT NULL,
    RE_TEMPO_USO DECIMAL(10,1) NOT NULL,
    RE_HORAS_MAO_OBRA DECIMAL(10,2) NOT NULL
);

-- ALTER TABLE para RECURSOS_ESPECIFICOS
ALTER TABLE RECURSOS_ESPECIFICOS ADD COLUMN RE_DESCRICAO TEXT;
ALTER TABLE RECURSOS_ESPECIFICOS CHANGE COLUMN RE_DESCRICAO RE_DESCRICAO_NOVA TEXT;
ALTER TABLE RECURSOS_ESPECIFICOS MODIFY COLUMN RE_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE RECURSOS_ESPECIFICOS DROP COLUMN RE_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS CARGOS(
    CAR_ID INT PRIMARY KEY,
    CAR_NOME VARCHAR(50) NOT NULL
);

-- ALTER TABLE para CARGOS
ALTER TABLE CARGOS ADD COLUMN CAR_DESCRICAO TEXT;
ALTER TABLE CARGOS CHANGE COLUMN CAR_DESCRICAO CAR_DESCRICAO_NOVA TEXT;
ALTER TABLE CARGOS MODIFY COLUMN CAR_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE CARGOS DROP COLUMN CAR_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS FUNCOES(
    FUN_ID INT PRIMARY KEY,
    FUN_NOME VARCHAR(50) NOT NULL
);

-- ALTER TABLE para FUNCOES
ALTER TABLE FUNCOES ADD COLUMN FUN_DESCRICAO TEXT;
ALTER TABLE FUNCOES CHANGE COLUMN FUN_DESCRICAO FUN_DESCRICAO_NOVA TEXT;
ALTER TABLE FUNCOES MODIFY COLUMN FUN_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE FUNCOES DROP COLUMN FUN_DESCRICAO_NOVA;

-- criando as tabelas com chave estrangeira

CREATE TABLE IF NOT EXISTS ENCOMENDAS(
    ENC_ID INT,
    ENC_DATA_INC DATE NOT NULL,
    ENC_VALOR_TOT DECIMAL(10,2) NOT NULL,
    ENC_VALOR_DESC DECIMAL(10,2) NOT NULL,
    ENC_VALOR_LIQ DECIMAL(10,2) NOT NULL,
    ENC_QTD_PARC INT,
    ENC_CLIENTE INT,
    PRIMARY KEY (ENC_ID, ENC_CLIENTE),
    CONSTRAINT FK_CLIENTE_ENC FOREIGN KEY (ENC_CLIENTE) REFERENCES CLIENTES(CLI_ID)
);

-- ALTER TABLE para ENCOMENDAS
ALTER TABLE ENCOMENDAS ADD COLUMN ENC_STATUS ENUM('PENDENTE', 'FINALIZADA', 'CANCELADA');
ALTER TABLE ENCOMENDAS CHANGE COLUMN ENC_STATUS ENC_STATUS_NOVO ENUM('PENDENTE', 'FINALIZADA', 'CANCELADA');
ALTER TABLE ENCOMENDAS MODIFY COLUMN ENC_STATUS_NOVO ENUM('PENDENTE', 'FINALIZADA', 'CANCELADA') NOT NULL;
ALTER TABLE ENCOMENDAS DROP COLUMN ENC_STATUS_NOVO;

CREATE TABLE IF NOT EXISTS PRODUTOS(
    PROD_ID INT,
    PROD_RE INT,
    PROD_NOME VARCHAR(50) NOT NULL,
    PROD_COR VARCHAR(50) NOT NULL,
    PROD_DIMENSOES VARCHAR(50) NOT NULL,
    PROD_PESO VARCHAR(50) NOT NULL,
    PROD_PRECO DECIMAL(10,2) NOT NULL,
    PROD_TEMPO_FAB VARCHAR(50) NOT NULL,
    PROD_DESENHO BLOB,
    PROD_HORAS_MAO_OBRA VARCHAR(50) NOT NULL,
    PRIMARY KEY (PROD_ID, PROD_RE),
    CONSTRAINT FK_RECURSOS_PROD FOREIGN KEY (PROD_RE) REFERENCES RECURSOS_ESPECIFICOS(RE_ID)
);

-- ALTER TABLE para PRODUTOS
ALTER TABLE PRODUTOS ADD COLUMN PROD_DESCRICAO TEXT;
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_DESCRICAO PROD_DESCRICAO_NOVA TEXT;
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE PRODUTOS DROP COLUMN PROD_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
    PAG_ID INT,
    PAG_CLIENTE INT,
    PAG_ENC INT,
    PRIMARY KEY (PAG_ID, PAG_CLIENTE, PAG_ENC),
    PAG_TIPO_FORMA VARCHAR(50) NOT NULL,
    PAG_VALOR_TOT DECIMAL(10,2),
    CONSTRAINT FK_CLIENTE_PAG FOREIGN KEY (PAG_CLIENTE) REFERENCES CLIENTES(CLI_ID),
    CONSTRAINT FK_ENCOMENDA_PAG FOREIGN KEY (PAG_ENC) REFERENCES ENCOMENDAS(ENC_ID)
);

-- ALTER TABLE para PAGAMENTOS
ALTER TABLE PAGAMENTOS ADD COLUMN PAG_DESCRICAO TEXT;
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAG_DESCRICAO PAG_DESCRICAO_NOVA TEXT;
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS REGISTRO_MANUTENCAO(
    RM_MAQUINA INT PRIMARY KEY,
    RM_DATA DATE NOT NULL,
    RM_DESC VARCHAR(100) NOT NULL,
    CONSTRAINT FK_MAQUINA_RM FOREIGN KEY(RM_MAQUINA) REFERENCES MAQUINAS(MAQ_ID)
);

-- ALTER TABLE para REGISTRO_MANUTENCAO
ALTER TABLE REGISTRO_MANUTENCAO ADD COLUMN RM_COMENTARIO TEXT;
ALTER TABLE REGISTRO_MANUTENCAO CHANGE COLUMN RM_COMENTARIO RM_COMENTARIO_NOVO TEXT;
ALTER TABLE REGISTRO_MANUTENCAO MODIFY COLUMN RM_COMENTARIO_NOVO TEXT NOT NULL;
ALTER TABLE REGISTRO_MANUTENCAO DROP COLUMN RM_COMENTARIO_NOVO;

CREATE TABLE IF NOT EXISTS REGISTRO_SUPRIMENTOS(
    RS_PRODUTO INT PRIMARY KEY,
    RS_QTD INT NOT NULL,
    RS_DATA_NEC DATE NOT NULL,
    CONSTRAINT FK_PRODUTOS_RS FOREIGN KEY(RS_PRODUTO) REFERENCES PRODUTOS(PROD_ID)
);

-- ALTER TABLE para REGISTRO_SUPRIMENTOS
ALTER TABLE REGISTRO_SUPRIMENTOS ADD COLUMN RS_DESCRICAO TEXT;
ALTER TABLE REGISTRO_SUPRIMENTOS CHANGE COLUMN RS_DESCRICAO RS_DESCRICAO_NOVA TEXT;
ALTER TABLE REGISTRO_SUPRIMENTOS MODIFY COLUMN RS_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE REGISTRO_SUPRIMENTOS DROP COLUMN RS_DESCRICAO_NOVA;

-- criando as tabelas das entidades associativas

CREATE TABLE IF NOT EXISTS PESSOA_CONTATO(
    PC_ID INT,
    PC_CLIENTE INT,
    PC_FORNECEDOR VARCHAR(14),
    PC_NOME VARCHAR(50) NOT NULL,
    PRIMARY KEY (PC_ID, PC_CLIENTE, PC_FORNECEDOR),
    CONSTRAINT FK_CLIENTE_PC FOREIGN KEY(PC_CLIENTE) REFERENCES CLIENTES(CLI_ID),
    CONSTRAINT FK_FORNECEDOR_PC FOREIGN KEY(PC_FORNECEDOR) REFERENCES FORNECEDORES(FORN_CNPJ)
);

-- ALTER TABLE para PESSOA_CONTATO
ALTER TABLE PESSOA_CONTATO ADD COLUMN PC_EMAIL VARCHAR(50);
ALTER TABLE PESSOA_CONTATO CHANGE COLUMN PC_EMAIL PC_EMAIL_NOVO VARCHAR(50);
ALTER TABLE PESSOA_CONTATO MODIFY COLUMN PC_EMAIL_NOVO VARCHAR(100);
ALTER TABLE PESSOA_CONTATO DROP COLUMN PC_EMAIL_NOVO;

CREATE TABLE IF NOT EXISTS CARGOS_FUNCOES(
    CF_CARGO INT,
    CF_FUNCAO INT,
    PRIMARY KEY (CF_CARGO, CF_FUNCAO),
    CONSTRAINT PKFK_CARGO_CF FOREIGN KEY(CF_CARGO) REFERENCES CARGOS(CAR_ID),
    CONSTRAINT PKFK_FUNCAO_CF FOREIGN KEY(CF_FUNCAO) REFERENCES FUNCOES(FUN_ID)
);

-- ALTER TABLE para CARGOS_FUNCOES
ALTER TABLE CARGOS_FUNCOES ADD COLUMN CF_DESCRICAO TEXT;
ALTER TABLE CARGOS_FUNCOES CHANGE COLUMN CF_DESCRICAO CF_DESCRICAO_NOVA TEXT;
ALTER TABLE CARGOS_FUNCOES MODIFY COLUMN CF_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE CARGOS_FUNCOES DROP COLUMN CF_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS EMPREGADOS(
    EMP_ID INT,
    EMP_FUN INT,
    EMP_CAR INT,
    PRIMARY KEY (EMP_ID, EMP_FUN, EMP_CAR),
    EMP_NOME VARCHAR(50) NOT NULL,
    EMP_SAL DECIMAL(10,2) NOT NULL,
    EMP_DATA_ADMIS DATE NOT NULL,
    EMP_QUALIFICACOES VARCHAR(50) NOT NULL,
    CONSTRAINT FK_CAR_FUN_EMP FOREIGN KEY(EMP_CAR, EMP_FUN) REFERENCES CARGOS_FUNCOES(CF_CARGO, CF_FUNCAO)
);

-- ALTER TABLE para EMPREGADOS
ALTER TABLE EMPREGADOS ADD COLUMN EMP_DESCRICAO TEXT;
ALTER TABLE EMPREGADOS CHANGE COLUMN EMP_DESCRICAO EMP_DESCRICAO_NOVA TEXT;
ALTER TABLE EMPREGADOS MODIFY COLUMN EMP_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE EMPREGADOS DROP COLUMN EMP_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS TELEFONES(
    TELE_CLIENTE INT,
    TELE_EMPREGADO INT,
    TELE_FORNECEDOR VARCHAR(14),
    TELE_NUMERO VARCHAR(20) NOT NULL,
    PRIMARY KEY(TELE_CLIENTE, TELE_EMPREGADO, TELE_FORNECEDOR),
    CONSTRAINT FK_CLIENTE_TELE FOREIGN KEY(TELE_CLIENTE) REFERENCES CLIENTES(CLI_ID),
    CONSTRAINT FK_EMPREGADO_TELE FOREIGN KEY(TELE_EMPREGADO) REFERENCES EMPREGADOS(EMP_ID),
    CONSTRAINT FK_FORNECEDOR_TELE FOREIGN KEY(TELE_FORNECEDOR) REFERENCES FORNECEDORES(FORN_CNPJ)
);

-- ALTER TABLE para TELEFONES
ALTER TABLE TELEFONES ADD COLUMN TELE_DESCRICAO TEXT;
ALTER TABLE TELEFONES CHANGE COLUMN TELE_DESCRICAO TELE_DESCRICAO_NOVA TEXT;
ALTER TABLE TELEFONES MODIFY COLUMN TELE_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE TELEFONES DROP COLUMN TELE_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS ENDERECOS(
    ENDE_CLIENTE INT,
    ENDE_EMPREGADO INT,
    ENDE_FORNECEDOR VARCHAR(14),
    PRIMARY KEY(ENDE_CLIENTE, ENDE_EMPREGADO, ENDE_FORNECEDOR),
    ENDE_TIPO VARCHAR(45) NOT NULL,
    ENDE_NUMERO INT,
    ENDE_LOGRADOURO VARCHAR(45) NOT NULL,
    ENDE_CEP VARCHAR(10) NOT NULL,
    ENDE_COMPLE VARCHAR(45) NOT NULL,
    ENDE_BAIRRO VARCHAR(45) NOT NULL,
    ENDE_CIDADE VARCHAR(45) NOT NULL,
    ENDE_ESTADO VARCHAR(45) NOT NULL,
    ENDE_PAIS VARCHAR(45) NOT NULL,
    CONSTRAINT FK_CLIENTE_ENDE FOREIGN KEY(ENDE_CLIENTE) REFERENCES CLIENTES(CLI_ID),
    CONSTRAINT FK_EMPREGADO_ENDE FOREIGN KEY(ENDE_EMPREGADO) REFERENCES EMPREGADOS(EMP_ID),
    CONSTRAINT FK_FORNECEDOR_ENDE FOREIGN KEY(ENDE_FORNECEDOR) REFERENCES FORNECEDORES(FORN_CNPJ)
);

-- ALTER TABLE para ENDERECOS
ALTER TABLE ENDERECOS ADD COLUMN ENDE_DESCRICAO TEXT;
ALTER TABLE ENDERECOS CHANGE COLUMN ENDE_DESCRICAO ENDE_DESCRICAO_NOVA TEXT;
ALTER TABLE ENDERECOS MODIFY COLUMN ENDE_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE ENDERECOS DROP COLUMN ENDE_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS PRODUTOS_EMPREGADOS(
    PREM_EMP INT,
    PREM_PROD INT,
    PRIMARY KEY(PREM_EMP, PREM_PROD),
    CONSTRAINT PKFK_PRODUTO_PREM FOREIGN KEY(PREM_PROD) REFERENCES PRODUTOS(PROD_ID),
    CONSTRAINT PKFK_EMPREGADO_PREM FOREIGN KEY(PREM_EMP) REFERENCES EMPREGADOS(EMP_ID)
);

-- ALTER TABLE para PRODUTOS_EMPREGADOS
ALTER TABLE PRODUTOS_EMPREGADOS ADD COLUMN PREM_DESCRICAO TEXT;
ALTER TABLE PRODUTOS_EMPREGADOS CHANGE COLUMN PREM_DESCRICAO PREM_DESCRICAO_NOVA TEXT;
ALTER TABLE PRODUTOS_EMPREGADOS MODIFY COLUMN PREM_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE PRODUTOS_EMPREGADOS DROP COLUMN PREM_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS FORNECEDOR_COMPONENTE(
    FOCO_FORNECEDOR VARCHAR(14),
    FOCO_COMPONENTE INT,
    PRIMARY KEY (FOCO_FORNECEDOR, FOCO_COMPONENTE),
    CONSTRAINT FK_FORNECEDOR_FOCO FOREIGN KEY(FOCO_FORNECEDOR) REFERENCES FORNECEDORES(FORN_CNPJ),
    CONSTRAINT FK_COMPONENTE_FOCO FOREIGN KEY(FOCO_COMPONENTE) REFERENCES COMPONENTES(COMP_ID)
);

-- ALTER TABLE para FORNECEDOR_COMPONENTE
ALTER TABLE FORNECEDOR_COMPONENTE ADD COLUMN FOCO_DESCRICAO TEXT;
ALTER TABLE FORNECEDOR_COMPONENTE CHANGE COLUMN FOCO_DESCRICAO FOCO_DESCRICAO_NOVA TEXT;
ALTER TABLE FORNECEDOR_COMPONENTE MODIFY COLUMN FOCO_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE FORNECEDOR_COMPONENTE DROP COLUMN FOCO_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS PRODUTOS_ENCOMENDA(
    PREN_PROD INT,
    PREN_ENC INT,
    PRIMARY KEY (PREN_PROD, PREN_ENC),
    CONSTRAINT FK_PRODUTO_PREN FOREIGN KEY(PREN_PROD) REFERENCES PRODUTOS(PROD_ID),
    CONSTRAINT FK_ENCOMENDA_PREN FOREIGN KEY(PREN_ENC) REFERENCES ENCOMENDAS(ENC_ID)
);

-- ALTER TABLE para PRODUTOS_ENCOMENDA
ALTER TABLE PRODUTOS_ENCOMENDA ADD COLUMN PREN_DESCRICAO TEXT;
ALTER TABLE PRODUTOS_ENCOMENDA CHANGE COLUMN PREN_DESCRICAO PREN_DESCRICAO_NOVA TEXT;
ALTER TABLE PRODUTOS_ENCOMENDA MODIFY COLUMN PREN_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE PRODUTOS_ENCOMENDA DROP COLUMN PREN_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS PRODUTOS_MAQUINA(
    PRMA_PROD INT,
    PRMA_MAQUINA INT,
    PRIMARY KEY (PRMA_PROD, PRMA_MAQUINA),
    CONSTRAINT FK_PRODUTO_PRMA FOREIGN KEY(PRMA_PROD) REFERENCES PRODUTOS(PROD_ID),
    CONSTRAINT FK_MAQUINA_PRMA FOREIGN KEY(PRMA_MAQUINA) REFERENCES MAQUINAS(MAQ_ID)
);

-- ALTER TABLE para PRODUTOS_MAQUINA
ALTER TABLE PRODUTOS_MAQUINA ADD COLUMN PRMA_DESCRICAO TEXT;
ALTER TABLE PRODUTOS_MAQUINA CHANGE COLUMN PRMA_DESCRICAO PRMA_DESCRICAO_NOVA TEXT;
ALTER TABLE PRODUTOS_MAQUINA MODIFY COLUMN PRMA_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE PRODUTOS_MAQUINA DROP COLUMN PRMA_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS PRODUTOS_TIPO_COMPONENTE(
    PRTC_PROD INT,
    PRTC_TC INT,
    PRIMARY KEY(PRTC_PROD, PRTC_TC),
    CONSTRAINT FK_PRODUTO_PRTC FOREIGN KEY(PRTC_PROD) REFERENCES PRODUTOS(PROD_ID),
    CONSTRAINT FK_TIPO_COMPONENTE_PRTC FOREIGN KEY(PRTC_TC) REFERENCES TIPO_COMPONENTES(TC_ID)
);

-- ALTER TABLE para PRODUTOS_TIPO_COMPONENTE
ALTER TABLE PRODUTOS_TIPO_COMPONENTE ADD COLUMN PRTC_DESCRICAO TEXT;
ALTER TABLE PRODUTOS_TIPO_COMPONENTE CHANGE COLUMN PRTC_DESCRICAO PRTC_DESCRICAO_NOVA TEXT;
ALTER TABLE PRODUTOS_TIPO_COMPONENTE MODIFY COLUMN PRTC_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE PRODUTOS_TIPO_COMPONENTE DROP COLUMN PRTC_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS PRODUTOS_CARGOS_FUNCOES (
    PFC_PROD INT,
    PFC_CF_CARGO INT,
    PFC_CF_FUNCAO INT,
    PRIMARY KEY (PFC_PROD, PFC_CF_CARGO, PFC_CF_FUNCAO),
    CONSTRAINT FK_PRODUTO_PFC FOREIGN KEY (PFC_PROD) REFERENCES PRODUTOS(PROD_ID),
    CONSTRAINT FK_CARGOS_FUNCOES_PFC FOREIGN KEY (PFC_CF_CARGO, PFC_CF_FUNCAO) REFERENCES CARGOS_FUNCOES(CF_CARGO, CF_FUNCAO)
);
-- ALTER TABLE para PRODUTOS_CARGOS_FUNCOES
ALTER TABLE PRODUTOS_CARGOS_FUNCOES ADD COLUMN PFC_DESCRICAO TEXT;
ALTER TABLE PRODUTOS_CARGOS_FUNCOES CHANGE COLUMN PFC_DESCRICAO PFC_DESCRICAO_NOVA TEXT;
ALTER TABLE PRODUTOS_CARGOS_FUNCOES MODIFY COLUMN PFC_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE PRODUTOS_CARGOS_FUNCOES DROP COLUMN PFC_DESCRICAO_NOVA;

CREATE TABLE IF NOT EXISTS PRODUTOS_MAQUINA_ENCOMENDA(
    PMEN_PROD INT,
    PMEN_MAQUINA INT,
    PMEN_ENC INT,
    PRIMARY KEY(PMEN_PROD, PMEN_MAQUINA, PMEN_ENC),
    CONSTRAINT FK_PRODUTO_MAQUINA_ENCOMENDA FOREIGN KEY(PMEN_PROD) REFERENCES PRODUTOS(PROD_ID),
    CONSTRAINT FK_MAQUINA_ENCOMENDA FOREIGN KEY(PMEN_MAQUINA) REFERENCES MAQUINAS(MAQ_ID),
    CONSTRAINT FK_ENCOMENDA_MAQUINA FOREIGN KEY(PMEN_ENC) REFERENCES ENCOMENDAS(ENC_ID)
);

-- ALTER TABLE para PRODUTOS_MAQUINA_ENCOMENDA
ALTER TABLE PRODUTOS_MAQUINA_ENCOMENDA ADD COLUMN PMEN_DESCRICAO TEXT;
ALTER TABLE PRODUTOS_MAQUINA_ENCOMENDA CHANGE COLUMN PMEN_DESCRICAO PMEN_DESCRICAO_NOVA TEXT;
ALTER TABLE PRODUTOS_MAQUINA_ENCOMENDA MODIFY COLUMN PMEN_DESCRICAO_NOVA TEXT NOT NULL;
ALTER TABLE PRODUTOS_MAQUINA_ENCOMENDA DROP COLUMN PMEN_DESCRICAO_NOVA;

-- criando a tabela extra e usando o drop 

CREATE TABLE IF NOT EXISTS EXEMPLO(
EXI int
);

DROP TABLE EXEMPLO;


