DROP SCHEMA IF EXISTS EST_CASOIV;
CREATE SCHEMA EST_CASOIV;
USE EST_CASOIV;

#criando as tabelas sem chaves estrangeiras

#criando tabela alunos
CREATE TABLE IF NOT EXISTS ALUNOS (
    ALUNO_ID INT PRIMARY KEY,
    ALUNO_NOME VARCHAR(45) NOT NULL,
    ALUNO_DATA_NASC DATE NOT NULL,
    ALUNO_CPF VARCHAR(11) NOT NULL,
    ALUNO_NUMERO_RUA INT,
    ALUNO_CIDADE VARCHAR(45) NOT NULL,
    ALUNO_ESTADO VARCHAR(45) NOT NULL,
    ALUNO_PAIS VARCHAR(45) NOT NULL,
    ALUNO_BAIRRO VARCHAR(30) NOT NULL,
    ALUNO_TELEFONE VARCHAR(15) NOT NULL
);

#criando alter da tabela alunos
ALTER TABLE ALUNOS ADD COLUMN ALUNO_EMAIL VARCHAR(50);
ALTER TABLE ALUNOS CHANGE COLUMN ALUNO_EMAIL ALUNO_EMAIL VARCHAR(50);
ALTER TABLE ALUNOS MODIFY COLUMN ALUNO_EMAIL VARCHAR(100);
ALTER TABLE ALUNOS DROP COLUMN ALUNO_EMAIL;

#criando tabela modalidades
CREATE TABLE IF NOT EXISTS MODALIDADES (
    MOD_ID INT PRIMARY KEY,
    MOD_NOME VARCHAR(45) NOT NULL,
    MOD_numInscritos int
);

#criando alter da tabela modalidades
ALTER TABLE MODALIDADES ADD COLUMN MOD_DESCRICAO VARCHAR(100);
ALTER TABLE MODALIDADES CHANGE COLUMN MOD_DESCRICAO MODALIDADE_DESCRICAO VARCHAR(100);
ALTER TABLE MODALIDADES MODIFY COLUMN MODALIDADE_DESCRICAO VARCHAR(150);
ALTER TABLE MODALIDADES DROP COLUMN MODALIDADE_DESCRICAO;

#criando tabela instrutores
CREATE TABLE IF NOT EXISTS INSTRUTORES (
    INST_ID INT PRIMARY KEY,
    INST_NOME VARCHAR(45) NOT NULL
);

#criando alter da tabela instrutores
ALTER TABLE INSTRUTORES ADD COLUMN INST_EMAIL VARCHAR(50);
ALTER TABLE INSTRUTORES CHANGE COLUMN INST_EMAIL INSTRUTOR_EMAIL VARCHAR(50);
ALTER TABLE INSTRUTORES MODIFY COLUMN INSTRUTOR_EMAIL VARCHAR(100);
ALTER TABLE INSTRUTORES DROP COLUMN INSTRUTOR_EMAIL;

#criando tabela pagamentos
CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    PG_ID INT PRIMARY KEY,
    PG_DATA DATE NOT NULL,
    PG_VALOR DECIMAL(10,2) NOT NULL,
    PG_STATUS VARCHAR(20) NOT NULL,
    PG_ALUNO_ID INT NOT NULL,
    CONSTRAINT FK_ALUNO_PAG FOREIGN KEY (PG_ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID)
);

#criando alter da tabela pagamentos
ALTER TABLE PAGAMENTOS ADD COLUMN PG_FORMA_PAGAMENTO VARCHAR(20);
ALTER TABLE PAGAMENTOS CHANGE COLUMN PG_FORMA_PAGAMENTO PAGAMENTO_FORMA VARCHAR(20);
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAGAMENTO_FORMA VARCHAR(30);
ALTER TABLE PAGAMENTOS DROP COLUMN PAGAMENTO_FORMA;

#criando tabela instrutores_modalidades
CREATE TABLE IF NOT EXISTS INSTRUTORES_MODALIDADES (
    instMod_INSTRUTOR_ID INT,
    instMod_MOD_ID INT,
    PRIMARY KEY (instMod_INSTRUTOR_ID, instMod_MOD_ID),
    CONSTRAINT PKFK_INSTRUTOR_INMO FOREIGN KEY (instMod_INSTRUTOR_ID) REFERENCES INSTRUTORES(INST_ID),
    CONSTRAINT PKFK_MODALIDADE_INMO FOREIGN KEY (instMod_MOD_ID) REFERENCES MODALIDADES(MOD_ID)
);

#criando alter da tabela instrutores_modalidades
ALTER TABLE INSTRUTORES_MODALIDADES ADD COLUMN instMod_TURNO VARCHAR(15);
ALTER TABLE INSTRUTORES_MODALIDADES CHANGE COLUMN instMod_TURNO INSTRUTOR_MODALIDADE_TURNO VARCHAR(15);
ALTER TABLE INSTRUTORES_MODALIDADES MODIFY COLUMN INSTRUTOR_MODALIDADE_TURNO VARCHAR(20);
ALTER TABLE INSTRUTORES_MODALIDADES DROP COLUMN INSTRUTOR_MODALIDADE_TURNO;

#criando tabela aulas
CREATE TABLE IF NOT EXISTS AULAS (
    AULA_ID INT,
    AULA_INSTRUTOR_ID INT,
    AULA_MODALIDADE_ID INT,
    AULA_CAPACIDADE INT NOT NULL,
    AULA_HORARIO TIME NOT NULL,
    PRIMARY KEY (AULA_ID, AULA_INSTRUTOR_ID, AULA_MODALIDADE_ID),
    CONSTRAINT FK_INMO_AUL FOREIGN KEY (AULA_INSTRUTOR_ID, AULA_MODALIDADE_ID)
    REFERENCES INSTRUTORES_MODALIDADES(instMod_INSTRUTOR_ID, instMod_MOD_ID)
);

#criando alter da tabela aulas
ALTER TABLE AULAS ADD COLUMN AULA_DESCRICAO VARCHAR(100);
ALTER TABLE AULAS CHANGE COLUMN AULA_DESCRICAO AULA_DESCRICAO VARCHAR(100);
ALTER TABLE AULAS MODIFY COLUMN AULA_DESCRICAO VARCHAR(150);
ALTER TABLE AULAS DROP COLUMN AULA_DESCRICAO;

#criando tabela planos_treinamento
CREATE TABLE IF NOT EXISTS PLANOS_TREINAMENTO (
    planTrein_ID INT,
    planTrein_DESCRICAO VARCHAR(200) NOT NULL,
    planTrein_DATA_CRIACAO DATE NOT NULL,
    planTrein_DATA_ATUALIZACAO DATE NOT NULL,
    planTrein_ALUNO_ID INT,
    planTrein_INSTRUTOR_ID INT,
    planTrein_MODALIDADE_ID INT,
    PRIMARY KEY (planTrein_ALUNO_ID, planTrein_INSTRUTOR_ID, planTrein_MODALIDADE_ID, planTrein_ID),
    CONSTRAINT FK_INMO_PLA FOREIGN KEY (planTrein_INSTRUTOR_ID, planTrein_MODALIDADE_ID)
    REFERENCES INSTRUTORES_MODALIDADES(instMod_INSTRUTOR_ID, instMod_MOD_ID),
    CONSTRAINT FK_ALUNO_PLA FOREIGN KEY (planTrein_ALUNO_ID)
    REFERENCES ALUNOS(ALUNO_ID)
);

#criando alter da tabela planos_treinamento
ALTER TABLE PLANOS_TREINAMENTO ADD COLUMN planTrein_STATUS ENUM('ATIVO', 'INATIVO');
ALTER TABLE PLANOS_TREINAMENTO CHANGE COLUMN planTrein_STATUS PLANO_STATUS ENUM('ATIVO', 'INATIVO');
ALTER TABLE PLANOS_TREINAMENTO MODIFY COLUMN PLANO_STATUS ENUM('ATIVO', 'INATIVO') NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO DROP COLUMN PLANO_STATUS;

#criando tabela aulas_alunos
CREATE TABLE IF NOT EXISTS AULAS_ALUNOS (
    aulaAluno_AULA_ID INT,
    aulaAluno_ALUNO_ID INT,
    PRIMARY KEY (aulaAluno_AULA_ID, aulaAluno_ALUNO_ID),
    CONSTRAINT PKFK_ALUNO_AULAS FOREIGN KEY (aulaAluno_ALUNO_ID)
    REFERENCES ALUNOS(ALUNO_ID),
    CONSTRAINT PKFK_AULA_AULAS FOREIGN KEY (aulaAluno_AULA_ID)
    REFERENCES AULAS(AULA_ID)
);

#criando alter da tabela aulas_alunos
ALTER TABLE AULAS_ALUNOS ADD COLUMN AULA_ALUNO_DATA DATE;
ALTER TABLE AULAS_ALUNOS CHANGE COLUMN AULA_ALUNO_DATA AULA_ALUNO_DATA DATE;
ALTER TABLE AULAS_ALUNOS MODIFY COLUMN AULA_ALUNO_DATA DATE NOT NULL;
ALTER TABLE AULAS_ALUNOS DROP COLUMN AULA_ALUNO_DATA;

CREATE TABLE IF NOT EXISTS FUNCIONAMENTO(
FUNCIONAMENTO_DATA DATE NOT NULL,
FUNCIONAMENTO_HORA TIME NOT NULL
);

DROP TABLE FUNCIONAMENTO;
