CREATE SCHEMA EST_CASOIV;
USE EST_CASOIV;

-- Criando tabelas sem chaves primárias
CREATE TABLE IF NOT EXISTS ALUNOS (
    ALUNO_ID INT PRIMARY KEY,
    ALUNO_NOME VARCHAR(45) NOT NULL,
    ALUNO_DATA_NASCIMENTO DATE NOT NULL,
    ALUNO_CPF VARCHAR(11) NOT NULL,
    ALUNO_NUMERO_RUA INT,
    ALUNO_CIDADE VARCHAR(45) NOT NULL,
    ALUNO_ESTADO VARCHAR(45) NOT NULL,
    ALUNO_PAIS VARCHAR(45) NOT NULL,
    ALUNO_BAIRRO VARCHAR(30) NOT NULL,
    ALUNO_TELEFONE VARCHAR(15) NOT NULL
);

-- Criando alter da tabela ALUNOS
ALTER TABLE ALUNOS ADD COLUMN EMAIL VARCHAR(50);
ALTER TABLE ALUNOS CHANGE COLUMN EMAIL ALUNO_EMAIL VARCHAR(50);
ALTER TABLE ALUNOS MODIFY COLUMN ALUNO_EMAIL VARCHAR(100);
ALTER TABLE ALUNOS DROP COLUMN ALUNO_EMAIL;

CREATE TABLE IF NOT EXISTS MODALIDADES (
    MOD_ID INT PRIMARY KEY,
    MOD_NOME VARCHAR(45) NOT NULL
);

-- Criando alter da tabela MODALIDADES
ALTER TABLE MODALIDADES ADD COLUMN DESCRICAO VARCHAR(100);
ALTER TABLE MODALIDADES CHANGE COLUMN DESCRICAO MOD_DESCRICAO VARCHAR(100);
ALTER TABLE MODALIDADES MODIFY COLUMN MOD_DESCRICAO VARCHAR(150);
ALTER TABLE MODALIDADES DROP COLUMN MOD_DESCRICAO;

CREATE TABLE IF NOT EXISTS INSTRUTORES (
    INST_ID INT PRIMARY KEY,
    INST_NOME VARCHAR(45) NOT NULL
);

-- Criando alter da tabela INSTRUTORES
ALTER TABLE INSTRUTORES ADD COLUMN EMAIL VARCHAR(50);
ALTER TABLE INSTRUTORES CHANGE COLUMN EMAIL INST_EMAIL VARCHAR(50);
ALTER TABLE INSTRUTORES MODIFY COLUMN INST_EMAIL VARCHAR(100);
ALTER TABLE INSTRUTORES DROP COLUMN INST_EMAIL;

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    PG_ID INT PRIMARY KEY,
    PG_DATA DATE NOT NULL,
    PG_VALOR DECIMAL(10,2) NOT NULL,
    PG_STATUS VARCHAR(20) NOT NULL,
    PG_ALUNO_ID INT NOT NULL
);

-- Criando alter da tabela PAGAMENTOS
ALTER TABLE PAGAMENTOS ADD COLUMN DESCRICAO VARCHAR(100);
ALTER TABLE PAGAMENTOS CHANGE COLUMN DESCRICAO PG_DESCRICAO VARCHAR(100);
ALTER TABLE PAGAMENTOS MODIFY COLUMN PG_DESCRICAO VARCHAR(150);
ALTER TABLE PAGAMENTOS DROP COLUMN PG_DESCRICAO;

CREATE TABLE IF NOT EXISTS INSTRUTORES_MODALIDADES (
    INSTMOD_INSTRUTOR_ID INT,
    INSTMOD_MOD_ID INT,
    PRIMARY KEY (INSTMOD_INSTRUTOR_ID, INSTMOD_MOD_ID),
    CONSTRAINT FK_INSTRUTOR FOREIGN KEY (INSTMOD_INSTRUTOR_ID) REFERENCES INSTRUTORES(INST_ID),
    CONSTRAINT FK_MODALIDADE FOREIGN KEY (INSTMOD_MOD_ID) REFERENCES MODALIDADES(MOD_ID)
);

-- Criando alter da tabela INSTRUTORES_MODALIDADES
ALTER TABLE INSTRUTORES_MODALIDADES ADD COLUMN CARGA_HORARIA INT;
ALTER TABLE INSTRUTORES_MODALIDADES CHANGE COLUMN CARGA_HORARIA INSTMOD_CARGA_HORARIA INT;
ALTER TABLE INSTRUTORES_MODALIDADES MODIFY COLUMN INSTMOD_CARGA_HORARIA INT NOT NULL;
ALTER TABLE INSTRUTORES_MODALIDADES DROP COLUMN INSTMOD_CARGA_HORARIA;

CREATE TABLE IF NOT EXISTS AULAS (
    AULA_ID INT PRIMARY KEY,
    AULA_INSTRUTOR_ID INT,
    AULA_MODALIDADE_ID INT,
    AULA_CAPACIDADE INT NOT NULL,
    AULA_HORARIO TIME NOT NULL,
    CONSTRAINT FK_AULAS_INSTRUTOR FOREIGN KEY (AULA_INSTRUTOR_ID) REFERENCES INSTRUTORES(INST_ID),
    CONSTRAINT FK_AULAS_MODALIDADE FOREIGN KEY (AULA_MODALIDADE_ID) REFERENCES MODALIDADES(MOD_ID)
);

-- Criando alter da tabela AULAS
ALTER TABLE AULAS ADD COLUMN DESCRICAO VARCHAR(100);
ALTER TABLE AULAS CHANGE COLUMN DESCRICAO AULA_DESCRICAO VARCHAR(100);
ALTER TABLE AULAS MODIFY COLUMN AULA_DESCRICAO VARCHAR(150);
ALTER TABLE AULAS DROP COLUMN AULA_DESCRICAO;

CREATE TABLE IF NOT EXISTS PLANOS_TREINAMENTO (
    PLAN_ID INT PRIMARY KEY,
    PLAN_DESCRICAO VARCHAR(200) NOT NULL,
    PLAN_DATA_CRIACAO DATE NOT NULL,
    PLAN_DATA_ATUALIZACAO DATE NOT NULL,
    PLAN_ALUNO_ID INT,
    PLAN_INSTRUTOR_ID INT,
    PLAN_MODALIDADE_ID INT,
    CONSTRAINT FK_PLAN_ALUNO FOREIGN KEY (PLAN_ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID),
    CONSTRAINT FK_PLAN_INSTRUTOR FOREIGN KEY (PLAN_INSTRUTOR_ID) REFERENCES INSTRUTORES(INST_ID),
    CONSTRAINT FK_PLAN_MODALIDADE FOREIGN KEY (PLAN_MODALIDADE_ID) REFERENCES MODALIDADES(MOD_ID)
);

-- Criando alter da tabela PLANOS_TREINAMENTO
ALTER TABLE PLANOS_TREINAMENTO ADD COLUMN OBSERVACOES TEXT;
ALTER TABLE PLANOS_TREINAMENTO CHANGE COLUMN OBSERVACOES PLAN_OBSERVACOES TEXT;
ALTER TABLE PLANOS_TREINAMENTO MODIFY COLUMN PLAN_OBSERVACOES TEXT NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO DROP COLUMN PLAN_OBSERVACOES;

CREATE TABLE IF NOT EXISTS AULAS_ALUNOS (
    AULA_ID INT,
    ALUNO_ID INT,
    PRIMARY KEY (AULA_ID, ALUNO_ID),
    CONSTRAINT FK_AULA FOREIGN KEY (AULA_ID) REFERENCES AULAS(AULA_ID),
    CONSTRAINT FK_ALUNO FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID)
);

-- Criando alter da tabela AULAS_ALUNOS
ALTER TABLE AULAS_ALUNOS ADD COLUMN STATUS ENUM('CONFIRMADA', 'PENDENTE', 'CANCELADA');
ALTER TABLE AULAS_ALUNOS CHANGE COLUMN STATUS AULA_ALUNO_STATUS ENUM('CONFIRMADA', 'PENDENTE', 'CANCELADA');
ALTER TABLE AULAS_ALUNOS MODIFY COLUMN AULA_ALUNO_STATUS ENUM('CONFIRMADA', 'PENDENTE', 'CANCELADA') NOT NULL;
ALTER TABLE AULAS_ALUNOS DROP COLUMN AULA_ALUNO_STATUS;

